comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /

articles:
    resource: "@ArticlesBundle/Controller/"
    type:     annotation
    prefix:   /

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /home

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    type: xml